[package]
name = "game_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.30.5"
ash = "0.38.0"
raw-window-handle = "0.6.2"
nalgebra-glm = "0.19.0"
log = "0.4.22"
env_logger = "0.11.5"
gpu-allocator = "0.27.0"
